<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Harold Kinds (SRA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="auditfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="auditfileVersion" fixed="CLAIR2.00.00">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="companyID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="taxRegistrationNr">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="companyName">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="companyAddress">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="companyCity">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="companyPostalCode">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fiscalYear">
								<xs:simpleType>
									<xs:restriction base="xs:positiveInteger">
										<xs:minInclusive value="1980"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="startDate" type="xs:date"/>
							<xs:element name="endDate" type="xs:date"/>
							<xs:element name="currencyCode">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dateCreated" type="xs:date"/>
							<xs:element name="productID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="productVersion">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="generalLedger">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="taxonomy">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ledgerAccount" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="accountID">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="accountDesc">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="accountType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="leadCode">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="leadDescription" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="customersSuppliers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="customerSupplier" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="custSupID">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="type" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="taxRegistrationNr" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="taxVerificationDate" type="xs:date" minOccurs="0"/>
										<xs:element name="companyName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="contact" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="streetAddress">
											<xs:complexType>
												<xs:sequence>
													<xs:choice>
														<xs:element name="address">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:sequence>
															<xs:element name="streetname">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:maxLength value="50"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:element>
															<xs:element name="number">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:maxLength value="15"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:element>
															<xs:element name="numberExtension" minOccurs="0">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:maxLength value="10"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:element>
														</xs:sequence>
													</xs:choice>
													<xs:element name="property" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="city">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="postalCode">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="10"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="region" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="country">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="postalAddress" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:choice>
														<xs:element name="address">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:sequence>
															<xs:element name="streetname">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:maxLength value="50"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:element>
															<xs:element name="number">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:maxLength value="15"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:element>
														</xs:sequence>
													</xs:choice>
													<xs:element name="city">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="postalCode">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="10"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="region" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="country">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="telephone" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="30"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="fax" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="30"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="eMail" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:token"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="website" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:token"/>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="transactions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="numberEntries" type="xs:nonNegativeInteger"/>
							<xs:element name="totalDebit" type="amount"/>
							<xs:element name="totalCredit" type="amount"/>
							<xs:element name="journal" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="journalID">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="20"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="description">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="type" type="xs:string" minOccurs="0"/>
										<xs:element name="transaction" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="transactionID">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="20"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="description" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="period">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="5"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="transactionDate" type="xs:date"/>
													<xs:element name="sourceID" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="line" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="recordID">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="20"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="accountID">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="15"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="custSupID" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="15"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="documentID" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="15"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="effectiveDate" type="xs:date" minOccurs="0"/>
																<xs:element name="description" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="50"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:choice>
																	<xs:element name="debitAmount" type="amount"/>
																	<xs:element name="creditAmount" type="amount"/>
																</xs:choice>
																<xs:element name="costDesc" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="50"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="productDesc" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="50"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="projectDesc" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:maxLength value="50"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="vat" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="vatCode" minOccurs="0">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:maxLength value="15"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:choice>
																				<xs:element name="vatPercentage" type="xs:double"/>
																				<xs:element name="vatAmount" type="amount"/>
																			</xs:choice>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="currency" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="currencyCode">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:maxLength value="3"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:choice>
																				<xs:element name="currencyDebitAmount" type="amount"/>
																				<xs:element name="currencyCreditAmount" type="amount"/>
																			</xs:choice>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="accountKey">
			<xs:selector xpath="./generalLedger/ledgerAccount"/>
			<xs:field xpath="accountID"/>
		</xs:key>
		<xs:keyref name="accountIDRef" refer="accountKey">
			<xs:selector xpath="./transactions/journal/transaction/line"/>
			<xs:field xpath="accountID"/>
		</xs:keyref>
		<xs:key name="customerSupplierKey">
			<xs:selector xpath="./customersSuppliers/customerSupplier"/>
			<xs:field xpath="custSupID"/>
		</xs:key>
		<xs:keyref name="custSupIDRef" refer="customerSupplierKey">
			<xs:selector xpath="./transactions/journal/transaction/line"/>
			<xs:field xpath="custSupID"/>
		</xs:keyref>
		<xs:key name="journalKey">
			<xs:selector xpath="./transactions/journal"/>
			<xs:field xpath="journalID"/>
		</xs:key>
		<xs:key name="transactionKey">
			<xs:selector xpath="./transactions/journal/transaction"/>
			<xs:field xpath="transactionID"/>
		</xs:key>
		<xs:key name="lineKey">
			<xs:selector xpath="./transactions/journal/transaction/line"/>
			<xs:field xpath="recordID"/>
		</xs:key>
	</xs:element>
	<xs:simpleType name="amount">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2"/>
			<xs:totalDigits value="20"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
