"""Generate the reference pages of the documentation from the code.

Writes
  docs/reference/codes.md   every finding code from ``pyxaf.findings.CODES``
  docs/reference/tables.md  every table schema from ``pyxaf.tables.TABLES``

Run after changing finding codes or table schemas (CI fails when the pages are stale):

    uv run python scripts/gen_docs.py           # rewrite the pages
    uv run python scripts/gen_docs.py --check   # exit 1 if a page is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import pyxaf.tables
from pyxaf.findings import CODES, Severity
from pyxaf.tables import TABLES

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
NOTICE = (
    "<!-- Generated by scripts/gen_docs.py from {source}. Do not edit by hand: change the code\n"
    "     and run `uv run python scripts/gen_docs.py` (CI checks that this page is current). -->\n"
)

GROUPS = {
    "1": ("Input container and character encoding", "L1"),
    "2": ("XML well-formedness and security", "L2"),
    "3": ("Version, namespace and structure", "L3, L4, L4x"),
    "4": ("References between records", "L5"),
    "5": ("Control totals and balance", "L6"),
    "6": ("Uniqueness", "L7"),
    "7": ("Data quality and conventions", "L8"),
    "8": ("RGS (Referentie Grootboekschema)", "L8"),
}

ARROW_TYPES = {"string": "utf8", "int64": "int64", "date": "date32", "bool": "bool"}


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render_codes() -> str:
    """Render docs/reference/codes.md."""
    out = [
        NOTICE.format(source="pyxaf.findings.CODES"),
        "# Finding codes",
        "",
        "Every problem pyxaf notices is reported as a `Finding` with a stable code",
        "`XAF<nnnn>`. The first digit groups the codes; the validation layer that produces",
        "them is noted per group (see [Validation](../guide/validation.md)). The severity",
        "shown is the default: the validator may adjust it for the detected version (for",
        "example, unknown elements are only a warning for the derived XAF 3.0/3.1",
        "catalogues), and `severity_overrides=` changes or silences any code.",
        "",
        "Codes of the official XAF 4.0 consistency rules end in the rule number: rule [0009] is ",
        "`XAF5009`. The same list is available offline with `pyxaf codes` or `pyxaf.CODES`.",
        "",
    ]
    counts = {s: sum(1 for c in CODES.values() if c.severity is s) for s in Severity}
    out += [
        f"{len(CODES)} codes: "
        + ", ".join(f"{counts[s]} {s.name}" for s in sorted(Severity, reverse=True))
        + ".",
        "",
    ]
    for digit, (title, layer) in GROUPS.items():
        codes = [c for c in CODES.values() if c.code[3] == digit]
        if not codes:
            continue
        out += [f"## {digit}xxx — {title}", "", f"Layer: {layer}.", ""]
        out += ["| Code | Default severity | Title | Official rule |", "|---|---|---|---|"]
        for c in codes:
            anchor = f'<span id="{c.code.lower()}"></span>`{c.code}`'
            out.append(f"| {anchor} | {c.severity.name} | {_cell(c.title)} | {c.rule_ref or ''} |")
        out.append("")
    unknown = sorted({c.code[3] for c in CODES.values()} - set(GROUPS))
    if unknown:
        raise SystemExit(f"codes in undocumented groups: {unknown}")
    return _page(out)


def _table_descriptions() -> dict[str, str]:
    """Row descriptions from the table in the ``pyxaf.tables`` module docstring."""
    doc = pyxaf.tables.__doc__ or ""
    found = {
        name: text.replace("``", "`")
        for name, text in re.findall(r"^``(\w+)``\s+(.+?)\s*$", doc, flags=re.MULTILINE)
    }
    missing = set(TABLES) - set(found)
    if missing:
        raise SystemExit(f"tables without a description in pyxaf.tables: {sorted(missing)}")
    return found


def render_tables() -> str:
    """Render docs/reference/tables.md."""
    desc = _table_descriptions()
    out = [
        NOTICE.format(source="pyxaf.tables.TABLES"),
        "# Table schemas",
        "",
        "The normalized tables have the same columns for every iteration of the auditfile.",
        "Columns a version does not have are null. See",
        "[Interoperability](../guide/interop.md) for how to export them.",
        "",
        "Logical types map to Arrow types as follows: `string` → `utf8`, `int64` → `int64`, ",
        "`date` → `date32`, `bool` → `bool`, `decimal(p,s)` → `decimal128(p,s)`. CSV and JSONL ",
        "write decimals as exact strings and dates as ISO 8601.",
        "",
        "| Table | Rows | Columns |",
        "|---|---|---|",
    ]
    for name, cols in TABLES.items():
        out.append(f"| [`{name}`](#{name}) | {_cell(desc[name])} | {len(cols)} |")
    out.append("")
    for name, cols in TABLES.items():
        out += [f"## `{name}` {{ #{name} }}", "", desc[name][0].upper() + desc[name][1:] + ".", ""]
        out += ["| Column | Logical type | Arrow type |", "|---|---|---|"]
        for c in cols:
            dec = c.decimal
            arrow = f"decimal128({dec[0]},{dec[1]})" if dec else ARROW_TYPES[c.type]
            out.append(f"| `{c.name}` | `{c.type}` | `{arrow}` |")
        out.append("")
    return _page(out)


def _page(lines: list[str]) -> str:
    """Join lines without trailing whitespace, ending in exactly one newline."""
    text = "\n".join(line.rstrip() for line in "\n".join(lines).splitlines())
    return text.rstrip("\n") + "\n"


def main() -> int:
    """Write the pages, or check that they are current."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if a page is out of date")
    args = parser.parse_args()
    pages = {"codes.md": render_codes(), "tables.md": render_tables()}
    stale = []
    for name, text in pages.items():
        path = REFERENCE / name
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("out of date (run `uv run python scripts/gen_docs.py`):", *stale, sep="\n  ")
        return 1
    for path in stale:
        print("wrote", path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
